<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ogonna Eli">

<title>WEEK 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="WEEK 4_files/libs/clipboard/clipboard.min.js"></script>
<script src="WEEK 4_files/libs/quarto-html/quarto.js"></script>
<script src="WEEK 4_files/libs/quarto-html/popper.min.js"></script>
<script src="WEEK 4_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="WEEK 4_files/libs/quarto-html/anchor.min.js"></script>
<link href="WEEK 4_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="WEEK 4_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="WEEK 4_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="WEEK 4_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="WEEK 4_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">WEEK 4</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ogonna Eli </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   4.0.0     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'nlme'

The following object is masked from 'package:dplyr':

    collapse</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggResidpanel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggResidpanel' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggeffects' was built under R version 4.4.3</code></pre>
</div>
</div>
<section id="exercise-1-trunk-flare" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1-trunk-flare"><strong>Exercise 1: Trunk Flare</strong></h2>
</section>
<section id="goal-explore-how-well-diameter-at-breast-height-dbh-predicts-trunk-flare-diameter-in-trees-and-determine-whether-the-relationship-differs-among-species.-specifically-determine-whether-a-gls-model-that-accounts-for-non-constant-variance-provides-a-better-fit-than-a-standard-linear-model." class="level2">
<h2 class="anchored" data-anchor-id="goal-explore-how-well-diameter-at-breast-height-dbh-predicts-trunk-flare-diameter-in-trees-and-determine-whether-the-relationship-differs-among-species.-specifically-determine-whether-a-gls-model-that-accounts-for-non-constant-variance-provides-a-better-fit-than-a-standard-linear-model.">Goal: Explore how well diameter at breast height (DBH) predicts trunk flare diameter in trees, and determine whether the relationship differs among species. Specifically, determine whether a GLS model that accounts for non-constant variance provides a better fit than a standard linear model.</h2>
<ol type="1">
<li><p><strong>Read the data</strong> from the <code>trunkfl.csv</code> file.</p></li>
<li><p><strong>View the first few lines</strong> of data to confirm successful import and examine the structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data_1 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"trunkfl.csv"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X City Species DBH   TF BLVD SidewalkDamage trunk_shape
1 1    6       2  23  8.7  0.0              0    Circular
2 2    6       2  21  6.5  8.5              0    Circular
3 3    6       2  21  6.8  6.0              1    Circular
4 4    6       2  16  6.7  6.0              1    Circular
5 5    6       2  16  9.0  6.0              0        Oval
6 6    6       2  28 12.7  9.0              1        Oval</code></pre>
</div>
</div></li>
<li><p><strong>Subset the data</strong> to include only Acer saccharinum (<em>Species = 4</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sub <span class="ot">&lt;-</span> data_1 <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Species <span class="sc">==</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Make a scatter plot</strong> of trunk flare vs.&nbsp;diameter at breast height (DBH) for Acer saccharinum. Include a fitted line.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sub, <span class="fu">aes</span>(<span class="at">x =</span> TF, <span class="at">y =</span> DBH)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p><strong>Fit a linear model</strong> relating trunk flare to DBH using <code>lm()</code>. Use residual plots to evaluate model assumptions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>lm_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(TF <span class="sc">~</span> DBH, <span class="at">data =</span> sub)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>lm_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = TF ~ DBH, data = sub)

Coefficients:
(Intercept)          DBH  
     0.1956       0.3844  </code></pre>
</div>
</div></li>
<li><p><strong>Fit a GLS model</strong> where variance increases with DBH using <code>varPower()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>varpow <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> DBH, <span class="at">weights =</span> <span class="fu">varPower</span>(<span class="at">form =</span> <span class="sc">~</span> TF), <span class="at">data =</span> sub)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>varpow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: TF ~ DBH 
  Data: sub 
  Log-restricted-likelihood: -128.1955

Coefficients:
(Intercept)         DBH 
 0.08458531  0.37350980 

Variance function:
 Structure: Power of variance covariate
 Formula: ~TF 
 Parameter estimates:
  power 
1.16808 
Degrees of freedom: 96 total; 94 residual
Residual standard error: 0.09610405 </code></pre>
</div>
</div></li>
<li><p><strong>Create diagnostic plots</strong> of standardized residuals from the GLS model. Check homogeneity and normality assumptions using residual vs.&nbsp;fitted, QQ plots, and histograms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ggResidpanel<span class="sc">::</span><span class="fu">resid_panel</span>(lm_1, <span class="at">plots =</span> <span class="fu">c</span>(<span class="st">"resid"</span>, <span class="st">"qq"</span>, <span class="st">"hist"</span>), <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.
ℹ The deprecated feature was likely used in the ggResidpanel package.
  Please report the issue to the authors.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
ℹ The deprecated feature was likely used in the ggResidpanel package.
  Please report the issue to the authors.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p><strong>Use AIC to compare models</strong>: Which model (LM vs GLS) gives the better fit?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(lm_1, varpow)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in AIC.default(lm_1, varpow): models are not all fitted to the same
number of observations</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
lm_1    3 315.1348
varpow  4 264.3910</code></pre>
</div>
</div>
<ul>
<li>The GLS model performs better since the AIC score is lower than the LM model.</li>
</ul></li>
<li><p><strong>Compare parameter estimates</strong> and their standard errors between LM and GLS. Do the estimates or inference change?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(lm_1, varpow)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in AIC.default(lm_1, varpow): models are not all fitted to the same
number of observations</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>       df      AIC
lm_1    3 315.1348
varpow  4 264.3910</code></pre>
</div>
</div></li>
<li><p><strong>Use the full dataset (all species)</strong> to:</p>
<ul>
<li><p>Fit a GLS model with the interaction between Species and DBH.</p></li>
<li><p>Identify the optimal variance structure.</p></li>
<li><p>Identify the optimal fixed effects structure (using AIC and nested model comparison).</p></li>
<li><p>Plot the final model and interpret the results.</p></li>
</ul>
<div id="comment">
<p>The full model performs better than the rest based on its lower AIC score</p>
</div></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Fit a GLS model with the interaction between Species and DBH.</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>varpow_2 <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> Species <span class="sc">*</span> DBH, <span class="at">weights =</span> <span class="fu">varPower</span>(<span class="at">form =</span> <span class="sc">~</span> Species), <span class="at">data =</span> data_1)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>varpow_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: TF ~ Species * DBH 
  Data: data_1 
  Log-restricted-likelihood: -1099.768

Coefficients:
(Intercept)     Species         DBH Species:DBH 
-2.23081450  0.70117284  0.52194284 -0.04469972 

Variance function:
 Structure: Power of variance covariate
 Formula: ~Species 
 Parameter estimates:
    power 
0.3157765 
Degrees of freedom: 619 total; 615 residual
Residual standard error: 0.8462644 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Identify the optimal variance structure.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># varIdent: different residual variances per Species</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>gls1 <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> Species <span class="sc">*</span> DBH, <span class="at">data =</span> data_1,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> Species))</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># varPower: variance depends on fitted values</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>gls2 <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> Species <span class="sc">*</span> DBH, <span class="at">data =</span> data_1,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">weights =</span> <span class="fu">varPower</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="fu">fitted</span>(.)))</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># varExp: variance increases exponentially with DBH</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>gls3 <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> Species <span class="sc">*</span> DBH, <span class="at">data =</span> data_1,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">weights =</span> <span class="fu">varExp</span>(<span class="at">form =</span> <span class="sc">~</span> DBH))</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="co"># varConstPower: flexible power function of DBH</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>gls4 <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> Species <span class="sc">*</span> DBH, <span class="at">data =</span> data_1,</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">weights =</span> <span class="fu">varConstPower</span>(<span class="at">form =</span> <span class="sc">~</span> DBH))</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co">#Identify the optimal fixed effects structure (using AIC and nested model comparison).</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>gls_full <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> Species <span class="sc">*</span> DBH, <span class="at">data =</span> data_1, <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>Species))</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>gls_no_inter <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> Species <span class="sc">+</span> DBH, <span class="at">data =</span> data_1, <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>Species))</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>gls_species <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> Species, <span class="at">data =</span> data_1, <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>Species))</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>gls_dbh <span class="ot">&lt;-</span> <span class="fu">gls</span>(TF <span class="sc">~</span> DBH, <span class="at">data =</span> data_1, <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>Species))</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare models</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(gls_full, gls_no_inter, gls_species, gls_dbh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in AIC.default(gls_full, gls_no_inter, gls_species, gls_dbh): models
are not all fitted to the same number of observations</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             df      AIC
gls_full      5 2232.468
gls_no_inter  4 2356.720
gls_species   3 2995.945
gls_dbh       3 2350.687</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(gls_full, gls_no_inter)  <span class="co"># Likelihood ratio test for interaction</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in nlme::anova.lme(object = gls_full, gls_no_inter): fitted objects
with different fixed effects. REML comparisons are not meaningful.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             Model df      AIC      BIC    logLik   Test  L.Ratio p-value
gls_full         1  5 2232.468 2254.576 -1111.234                        
gls_no_inter     2  4 2356.720 2374.413 -1174.360 1 vs 2 126.2523  &lt;.0001</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Plot the final model and interpret the results.</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create predicted values</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>data_1<span class="sc">$</span>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(gls_full)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_1, <span class="fu">aes</span>(<span class="at">x =</span> DBH, <span class="at">y =</span> TF, <span class="at">color =</span> Species)) <span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"GLS model: TF ~ Species * DBH"</span>,</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"TF"</span>,</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"DBH"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="exercise-2-benthic-biodiversity" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2-benthic-biodiversity"><strong>Exercise 2: Benthic Biodiversity</strong></h2>
</section>
<section id="goal-evaluate-how-nutrient-concentration-in-benthic-mesocosms-is-influenced-by-macrofaunal-biomass-enrichment-algae-and-nutrient-type.-test-for-and-model-heteroscedasticity-using-gls-and-identify-the-optimal-fixed-and-variance-structure-for-the-data.-examine-how-model-results-change-when-a-potential-outlier-is-removed." class="level2">
<h2 class="anchored" data-anchor-id="goal-evaluate-how-nutrient-concentration-in-benthic-mesocosms-is-influenced-by-macrofaunal-biomass-enrichment-algae-and-nutrient-type.-test-for-and-model-heteroscedasticity-using-gls-and-identify-the-optimal-fixed-and-variance-structure-for-the-data.-examine-how-model-results-change-when-a-potential-outlier-is-removed.">Goal: Evaluate how nutrient concentration in benthic mesocosms is influenced by macrofaunal biomass, enrichment (algae), and nutrient type. Test for and model heteroscedasticity using GLS, and identify the optimal fixed and variance structure for the data. Examine how model results change when a potential outlier is removed.</h2>
<ol type="1">
<li><p><strong>Read the data</strong> from the <code>Biodiversity.csv</code> file.</p></li>
<li><p><strong>Check the structure</strong> of the dataset and confirm it imported correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>data_2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Biodiversity.csv"</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   108 obs. of  7 variables:
 $ MU           : int  1 1 1 2 2 2 3 3 3 4 ...
 $ Mesocosm     : int  1 1 1 2 2 2 3 3 3 4 ...
 $ Abundance    : int  0 0 0 4 4 4 8 8 8 8 ...
 $ Biomass      : num  0 0 0 0.5 0.5 0.5 1 1 1 1 ...
 $ Treatment    : chr  "NoAlgae" "NoAlgae" "NoAlgae" "NoAlgae" ...
 $ Nutrient     : chr  "NO3" "NO3" "NO3" "NO3" ...
 $ Concentration: num  2.49 1.18 3.83 3.04 2.19 ...</code></pre>
</div>
</div></li>
<li><p><strong>Create a boxplot</strong> showing the variation in concentration for each nutrient–enrichment combination. Is there visual evidence of heterogeneity?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'viridis' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: viridisLite</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to factors</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>data_2<span class="sc">$</span>Nutrient <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data_2<span class="sc">$</span>Nutrient)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>data_2<span class="sc">$</span>Treatment <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data_2<span class="sc">$</span>Treatment)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_2, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">interaction</span>(Nutrient, Treatment), <span class="at">y =</span> Concentration, <span class="at">fill =</span> Treatment)) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p><strong>Fit a linear model</strong> using biomass, enrichment, nutrient, all two-way interactions, and the three-way interaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>lm_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Biomass <span class="sc">~</span> Treatment <span class="sc">*</span> Nutrient, <span class="at">data =</span> data_2)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Biomass ~ Treatment * Nutrient, data = data_2)

Residuals:
   Min     1Q Median     3Q    Max 
  -1.0   -0.5    0.0    0.5    1.0 

Coefficients:
                               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   1.000e+00  1.566e-01   6.387 5.08e-09 ***
TreatmentNoAlgae              2.477e-15  2.214e-01   0.000        1    
NutrientNO3                   2.355e-15  2.214e-01   0.000        1    
NutrientPO3                   1.583e-15  2.214e-01   0.000        1    
TreatmentNoAlgae:NutrientNO3 -4.267e-15  3.131e-01   0.000        1    
TreatmentNoAlgae:NutrientPO3 -2.460e-15  3.131e-01   0.000        1    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6642 on 102 degrees of freedom
Multiple R-squared:  1.43e-30,  Adjusted R-squared:  -0.04902 
F-statistic: 2.917e-29 on 5 and 102 DF,  p-value: 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>lm_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Biomass <span class="sc">~</span> Treatment <span class="sc">*</span> Nutrient <span class="sc">*</span> Concentration, <span class="at">data =</span> data_2)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Biomass ~ Treatment * Nutrient * Concentration, 
    data = data_2)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.42996 -0.46411  0.00107  0.49258  1.19681 

Coefficients:
                                            Estimate Std. Error t value
(Intercept)                                 0.701629   0.390301   1.798
TreatmentNoAlgae                            0.057470   0.447322   0.128
NutrientNO3                                 0.296910   0.421359   0.705
NutrientPO3                                 0.056980   0.593065   0.096
Concentration                               0.018907   0.022755   0.831
TreatmentNoAlgae:NutrientNO3                0.837843   0.663940   1.262
TreatmentNoAlgae:NutrientPO3               -0.306298   0.702853  -0.436
TreatmentNoAlgae:Concentration              0.203376   0.145871   1.394
NutrientNO3:Concentration                  -0.005825   0.383812  -0.015
NutrientPO3:Concentration                   0.080841   0.174849   0.462
TreatmentNoAlgae:NutrientNO3:Concentration -0.607926   0.452686  -1.343
TreatmentNoAlgae:NutrientPO3:Concentration  0.422780   0.455318   0.929
                                           Pr(&gt;|t|)  
(Intercept)                                  0.0754 .
TreatmentNoAlgae                             0.8980  
NutrientNO3                                  0.4827  
NutrientPO3                                  0.9237  
Concentration                                0.4081  
TreatmentNoAlgae:NutrientNO3                 0.2100  
TreatmentNoAlgae:NutrientPO3                 0.6640  
TreatmentNoAlgae:Concentration               0.1665  
NutrientNO3:Concentration                    0.9879  
NutrientPO3:Concentration                    0.6449  
TreatmentNoAlgae:NutrientNO3:Concentration   0.1825  
TreatmentNoAlgae:NutrientPO3:Concentration   0.3555  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6487 on 96 degrees of freedom
Multiple R-squared:  0.1023,    Adjusted R-squared:  -0.0005692 
F-statistic: 0.9945 on 11 and 96 DF,  p-value: 0.4571</code></pre>
</div>
</div></li>
<li><p><strong>Examine residual plots</strong>. Is the homogeneity of variance assumption met?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-14-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p><strong>Plot residuals vs predictors</strong> (biomass, treatment, nutrient). Which variable(s) may be driving the heterogeneity?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract residuals from the model</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>residuals_lm <span class="ot">&lt;-</span> <span class="fu">residuals</span>(lm_2)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Base R plots</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))  <span class="co"># 3 plots in one row</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Residuals vs Biomass (not typical since Biomass is response, usually vs fitted values)</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm_2<span class="sc">$</span>fitted.values, residuals_lm,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Fitted Biomass"</span>,</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Residuals vs Fitted"</span>)</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Residuals vs Treatment</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_2<span class="sc">$</span>Treatment, residuals_lm,</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Treatment"</span>,</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Residuals vs Treatment"</span>)</span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Residuals vs Nutrient</span></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data_2<span class="sc">$</span>Nutrient, residuals_lm,</span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Nutrient"</span>,</span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Residuals"</span>,</span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Residuals vs Nutrient"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p><strong>Fit GLS models</strong> using different variance structures:</p>
<ul>
<li><p>One accounting for treatment.</p></li>
<li><p>One accounting for nutrient.</p></li>
<li><p>One accounting for both treatment and nutrient interaction.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. GLS model accounting for heterogeneity by Treatment</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>gls_treat <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  Biomass <span class="sc">~</span> Treatment <span class="sc">*</span> Nutrient,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_2,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> Treatment)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. GLS model accounting for heterogeneity by Nutrient</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>gls_nutr <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  Biomass <span class="sc">~</span> Treatment <span class="sc">*</span> Nutrient,</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_2,</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> Nutrient)</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure factors are properly defined</span></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>data_2<span class="sc">$</span>Treatment <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data_2<span class="sc">$</span>Treatment)</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>data_2<span class="sc">$</span>Nutrient <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data_2<span class="sc">$</span>Nutrient)</span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an interaction factor</span></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>data_2<span class="sc">$</span>TreatNutr <span class="ot">&lt;-</span> <span class="fu">interaction</span>(data_2<span class="sc">$</span>Treatment, data_2<span class="sc">$</span>Nutrient)</span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a><span class="co"># GLS model with variance by Treatment:Nutrient interaction</span></span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a>gls_inter <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>  Biomass <span class="sc">~</span> Treatment <span class="sc">*</span> Nutrient,</span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_2,</span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> TreatNutr)</span>
<span id="cb50-27"><a href="#cb50-27" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Compare GLS models</strong> using <code>anova()</code>. Which model best accounts for heterogeneity? Plot residuals to confirm.</p>
<ul>
<li>The model that best accounts for heterogeneity is the model with only the treatment since the AIC score is the lowest. The loglikelihood is similar so I judged with AIC</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare variance structures with likelihood ratio tests</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(gls_treat, gls_nutr, gls_inter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Model df     AIC      BIC   logLik   Test L.Ratio p-value
gls_treat     1  8 239.338 260.3378 -111.669                       
gls_nutr      2  9 241.338 264.9628 -111.669 1 vs 2       0       1
gls_inter     3 12 247.338 278.8377 -111.669 2 vs 3       0       1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot residual from model with lowest AIC</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gls_treat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract residuals</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>resid_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fitted =</span> <span class="fu">fitted</span>(gls_treat),</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">residuals =</span> <span class="fu">resid</span>(gls_treat, <span class="at">type =</span> <span class="st">"normalized"</span>),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Treatment =</span> data_2<span class="sc">$</span>Treatment,</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Nutrient =</span> data_2<span class="sc">$</span>Nutrient,</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">TreatNutr =</span> data_2<span class="sc">$</span>TreatNutr</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>resid_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    fitted     residuals Treatment Nutrient   TreatNutr
1        1 -1.505545e+00   NoAlgae      NO3 NoAlgae.NO3
2        1 -1.505545e+00   NoAlgae      NO3 NoAlgae.NO3
3        1 -1.505545e+00   NoAlgae      NO3 NoAlgae.NO3
4        1 -7.527727e-01   NoAlgae      NO3 NoAlgae.NO3
5        1 -7.527727e-01   NoAlgae      NO3 NoAlgae.NO3
6        1 -7.527727e-01   NoAlgae      NO3 NoAlgae.NO3
7        1  1.337193e-15   NoAlgae      NO3 NoAlgae.NO3
8        1  1.337193e-15   NoAlgae      NO3 NoAlgae.NO3
9        1  1.337193e-15   NoAlgae      NO3 NoAlgae.NO3
10       1  1.337193e-15   NoAlgae      NO3 NoAlgae.NO3
11       1  1.337193e-15   NoAlgae      NO3 NoAlgae.NO3
12       1  1.337193e-15   NoAlgae      NO3 NoAlgae.NO3
13       1  7.527727e-01   NoAlgae      NO3 NoAlgae.NO3
14       1  7.527727e-01   NoAlgae      NO3 NoAlgae.NO3
15       1  7.527727e-01   NoAlgae      NO3 NoAlgae.NO3
16       1  1.505545e+00   NoAlgae      NO3 NoAlgae.NO3
17       1  1.505545e+00   NoAlgae      NO3 NoAlgae.NO3
18       1  1.505545e+00   NoAlgae      NO3 NoAlgae.NO3
19       1 -1.505545e+00     Algae      NO3   Algae.NO3
20       1 -1.505545e+00     Algae      NO3   Algae.NO3
21       1 -1.505545e+00     Algae      NO3   Algae.NO3
22       1 -7.527727e-01     Algae      NO3   Algae.NO3
23       1 -7.527727e-01     Algae      NO3   Algae.NO3
24       1 -7.527727e-01     Algae      NO3   Algae.NO3
25       1 -1.337193e-15     Algae      NO3   Algae.NO3
26       1 -1.337193e-15     Algae      NO3   Algae.NO3
27       1 -1.337193e-15     Algae      NO3   Algae.NO3
28       1 -1.337193e-15     Algae      NO3   Algae.NO3
29       1 -1.337193e-15     Algae      NO3   Algae.NO3
30       1 -1.337193e-15     Algae      NO3   Algae.NO3
31       1  7.527727e-01     Algae      NO3   Algae.NO3
32       1  7.527727e-01     Algae      NO3   Algae.NO3
33       1  7.527727e-01     Algae      NO3   Algae.NO3
34       1  1.505545e+00     Algae      NO3   Algae.NO3
35       1  1.505545e+00     Algae      NO3   Algae.NO3
36       1  1.505545e+00     Algae      NO3   Algae.NO3
37       1 -1.505545e+00   NoAlgae      NH4 NoAlgae.NH4
38       1 -1.505545e+00   NoAlgae      NH4 NoAlgae.NH4
39       1 -1.505545e+00   NoAlgae      NH4 NoAlgae.NH4
40       1 -7.527727e-01   NoAlgae      NH4 NoAlgae.NH4
41       1 -7.527727e-01   NoAlgae      NH4 NoAlgae.NH4
42       1 -7.527727e-01   NoAlgae      NH4 NoAlgae.NH4
43       1 -1.337193e-15   NoAlgae      NH4 NoAlgae.NH4
44       1 -1.337193e-15   NoAlgae      NH4 NoAlgae.NH4
45       1 -1.337193e-15   NoAlgae      NH4 NoAlgae.NH4
46       1 -1.337193e-15   NoAlgae      NH4 NoAlgae.NH4
47       1 -1.337193e-15   NoAlgae      NH4 NoAlgae.NH4
48       1 -1.337193e-15   NoAlgae      NH4 NoAlgae.NH4
49       1  7.527727e-01   NoAlgae      NH4 NoAlgae.NH4
50       1  7.527727e-01   NoAlgae      NH4 NoAlgae.NH4
51       1  7.527727e-01   NoAlgae      NH4 NoAlgae.NH4
52       1  1.505545e+00   NoAlgae      NH4 NoAlgae.NH4
53       1  1.505545e+00   NoAlgae      NH4 NoAlgae.NH4
54       1  1.505545e+00   NoAlgae      NH4 NoAlgae.NH4
55       1 -1.505545e+00     Algae      NH4   Algae.NH4
56       1 -1.505545e+00     Algae      NH4   Algae.NH4
57       1 -1.505545e+00     Algae      NH4   Algae.NH4
58       1 -7.527727e-01     Algae      NH4   Algae.NH4
59       1 -7.527727e-01     Algae      NH4   Algae.NH4
60       1 -7.527727e-01     Algae      NH4   Algae.NH4
61       1  2.340087e-15     Algae      NH4   Algae.NH4
62       1  2.340087e-15     Algae      NH4   Algae.NH4
63       1  2.340087e-15     Algae      NH4   Algae.NH4
64       1  2.340087e-15     Algae      NH4   Algae.NH4
65       1  2.340087e-15     Algae      NH4   Algae.NH4
66       1  2.340087e-15     Algae      NH4   Algae.NH4
67       1  7.527727e-01     Algae      NH4   Algae.NH4
68       1  7.527727e-01     Algae      NH4   Algae.NH4
69       1  7.527727e-01     Algae      NH4   Algae.NH4
70       1  1.505545e+00     Algae      NH4   Algae.NH4
71       1  1.505545e+00     Algae      NH4   Algae.NH4
72       1  1.505545e+00     Algae      NH4   Algae.NH4
73       1 -1.505545e+00   NoAlgae      PO3 NoAlgae.PO3
74       1 -1.505545e+00   NoAlgae      PO3 NoAlgae.PO3
75       1 -1.505545e+00   NoAlgae      PO3 NoAlgae.PO3
76       1 -7.527727e-01   NoAlgae      PO3 NoAlgae.PO3
77       1 -7.527727e-01   NoAlgae      PO3 NoAlgae.PO3
78       1 -7.527727e-01   NoAlgae      PO3 NoAlgae.PO3
79       1  0.000000e+00   NoAlgae      PO3 NoAlgae.PO3
80       1  0.000000e+00   NoAlgae      PO3 NoAlgae.PO3
81       1  0.000000e+00   NoAlgae      PO3 NoAlgae.PO3
82       1  0.000000e+00   NoAlgae      PO3 NoAlgae.PO3
83       1  0.000000e+00   NoAlgae      PO3 NoAlgae.PO3
84       1  0.000000e+00   NoAlgae      PO3 NoAlgae.PO3
85       1  7.527727e-01   NoAlgae      PO3 NoAlgae.PO3
86       1  7.527727e-01   NoAlgae      PO3 NoAlgae.PO3
87       1  7.527727e-01   NoAlgae      PO3 NoAlgae.PO3
88       1  1.505545e+00   NoAlgae      PO3 NoAlgae.PO3
89       1  1.505545e+00   NoAlgae      PO3 NoAlgae.PO3
90       1  1.505545e+00   NoAlgae      PO3 NoAlgae.PO3
91       1 -1.505545e+00     Algae      PO3   Algae.PO3
92       1 -1.505545e+00     Algae      PO3   Algae.PO3
93       1 -1.505545e+00     Algae      PO3   Algae.PO3
94       1 -7.527727e-01     Algae      PO3   Algae.PO3
95       1 -7.527727e-01     Algae      PO3   Algae.PO3
96       1 -7.527727e-01     Algae      PO3   Algae.PO3
97       1  0.000000e+00     Algae      PO3   Algae.PO3
98       1  0.000000e+00     Algae      PO3   Algae.PO3
99       1  0.000000e+00     Algae      PO3   Algae.PO3
100      1  0.000000e+00     Algae      PO3   Algae.PO3
101      1  0.000000e+00     Algae      PO3   Algae.PO3
102      1  0.000000e+00     Algae      PO3   Algae.PO3
103      1  7.527727e-01     Algae      PO3   Algae.PO3
104      1  7.527727e-01     Algae      PO3   Algae.PO3
105      1  7.527727e-01     Algae      PO3   Algae.PO3
106      1  1.505545e+00     Algae      PO3   Algae.PO3
107      1  1.505545e+00     Algae      PO3   Algae.PO3
108      1  1.505545e+00     Algae      PO3   Algae.PO3</code></pre>
</div>
</div></li>
<li><p><strong>Use ML estimation</strong> to test and refine the fixed effects structure:</p>
<ul>
<li><p>Test the 3-way interaction.</p></li>
<li><p>Drop insignificant two-way interactions one at a time using likelihood ratio tests.</p></li>
<li><p>Finalize the fixed effects.</p>
<ul>
<li>The model without any interaction is the best performing model since the AIC is lower</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit full model with ML (required for likelihood ratio tests)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>gls_full_ML <span class="ot">&lt;-</span> <span class="fu">gls</span>(Biomass <span class="sc">~</span> Treatment <span class="sc">*</span> Nutrient,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> data_2,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> Treatment),  <span class="co"># best variance structure</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"ML"</span>)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop 2-way interaction for testing</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>gls_no_inter <span class="ot">&lt;-</span> <span class="fu">update</span>(gls_full_ML, . <span class="sc">~</span> . <span class="sc">-</span> Treatment<span class="sc">:</span>Nutrient)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(gls_full_ML, gls_no_inter)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Model df      AIC      BIC    logLik   Test      L.Ratio p-value
gls_full_ML      1  8 227.9401 249.3972 -105.9701                            
gls_no_inter     2  6 223.9401 240.0329 -105.9701 1 vs 2 1.136868e-13       1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>gls_no_inter</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by maximum likelihood
  Model: Biomass ~ Treatment + Nutrient 
  Data: data_2 
  Log-likelihood: -105.97

Coefficients:
     (Intercept) TreatmentNoAlgae      NutrientNO3      NutrientPO3 
    1.000000e+00     2.350288e-16     2.219601e-16     3.532708e-16 

Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | Treatment 
 Parameter estimates:
NoAlgae   Algae 
      1       1 
Degrees of freedom: 108 total; 104 residual
Residual standard error: 0.6454972 </code></pre>
</div>
</div></li>
<li><p><strong>Fit the final model using REML</strong>. Check model assumptions. Identify any influential outliers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Refit final model with REML</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>gls_final <span class="ot">&lt;-</span> <span class="fu">gls</span>(<span class="fu">formula</span>(gls_no_inter), </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> data_2, </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> Treatment), </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">"REML"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></li>
<li><p><strong>Summarize and visualize the final model.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gls_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: formula(gls_no_inter) 
  Data: data_2 
       AIC      BIC    logLik
  234.0619 249.9282 -111.0309

Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | Treatment 
 Parameter estimates:
NoAlgae   Algae 
      1       1 

Coefficients:
                 Value Std.Error  t-value p-value
(Intercept)          1 0.1265924 7.899367       0
TreatmentNoAlgae     0 0.1265924 0.000000       1
NutrientNO3          0 0.1550434 0.000000       1
NutrientPO3          0 0.1550434 0.000000       1

 Correlation: 
                 (Intr) TrtmNA NtrNO3
TreatmentNoAlgae -0.500              
NutrientNO3      -0.612  0.000       
NutrientPO3      -0.612  0.000  0.500

Standardized residuals:
          Min            Q1           Med            Q3           Max 
-1.520234e+00 -7.601170e-01  8.438993e-17  7.601170e-01  1.520234e+00 

Residual standard error: 0.6577935 
Degrees of freedom: 108 total; 104 residual</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gls_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">ggpredict</span>(gls_final), <span class="at">show_data=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.
Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$Treatment</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$Nutrient</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-20-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
<li><p><strong>Refit the model without the outlier.</strong> Redo model selection and comparison. How do results change?</p>
<ul>
<li>The AIC reduced when I took out the outlier. The model without interaction is still the better performing model in both situation but the AIC drop after taking out the outlier.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardized residuals</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>resid_std <span class="ot">&lt;-</span> <span class="fu">resid</span>(gls_final, <span class="at">type =</span> <span class="st">"normalized"</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the index of the largest absolute residual</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(<span class="fu">abs</span>(resid_std))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>70 
70 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="do">##take out the outlier</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>data_no_outlier <span class="ot">&lt;-</span> data_2[<span class="sc">-</span><span class="fu">which.max</span>(<span class="fu">abs</span>(resid_std)), ]</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Refit the model without the outlier</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>gls_no_outlier <span class="ot">&lt;-</span> <span class="fu">gls</span>(Biomass <span class="sc">~</span> Treatment <span class="sc">*</span> Nutrient,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> data_no_outlier,</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> Treatment),</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gls_no_outlier)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: Biomass ~ Treatment * Nutrient 
  Data: data_no_outlier 
       AIC      BIC    logLik
  235.8413 256.7623 -109.9207

Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | Treatment 
 Parameter estimates:
  NoAlgae     Algae 
1.0000000 0.9859008 

Coefficients:
                                  Value Std.Error   t-value p-value
(Intercept)                   0.9411765 0.1588236  5.925925  0.0000
TreatmentNoAlgae              0.0588235 0.2230128  0.263767  0.7925
NutrientNO3                   0.0588235 0.2214689  0.265606  0.7911
NutrientPO3                   0.0588235 0.2214689  0.265606  0.7911
TreatmentNoAlgae:NutrientNO3 -0.0588235 0.3131582 -0.187840  0.8514
TreatmentNoAlgae:NutrientPO3 -0.0588235 0.3131582 -0.187840  0.8514

 Correlation: 
                             (Intr) TrtmNA NtrNO3 NtrPO3 TNA:NN
TreatmentNoAlgae             -0.712                            
NutrientNO3                  -0.717  0.511                     
NutrientPO3                  -0.717  0.511  0.514              
TreatmentNoAlgae:NutrientNO3  0.507 -0.712 -0.707 -0.364       
TreatmentNoAlgae:NutrientPO3  0.507 -0.712 -0.364 -0.707  0.507

Standardized residuals:
          Min            Q1           Med            Q3           Max 
-1.527076e+00 -7.527727e-01  1.695395e-15  7.527727e-01  1.616904e+00 

Residual standard error: 0.6642111 
Degrees of freedom: 107 total; 101 residual</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Redo model selection and comparison</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>gls_reduced <span class="ot">&lt;-</span> <span class="fu">update</span>(gls_no_outlier, . <span class="sc">~</span> . <span class="sc">-</span> Treatment<span class="sc">:</span>Nutrient)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(gls_no_outlier, gls_reduced)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in nlme::anova.lme(object = gls_no_outlier, gls_reduced): fitted
objects with different fixed effects. REML comparisons are not meaningful.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>               Model df      AIC      BIC    logLik   Test  L.Ratio p-value
gls_no_outlier     1  8 235.8413 256.7623 -109.9207                        
gls_reduced        2  6 230.6036 246.4120 -109.3018 1 vs 2 1.237691  0.5386</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(gls_no_outlier, gls_reduced)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in AIC.default(gls_no_outlier, gls_reduced): models are not all fitted
to the same number of observations</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>               df      AIC
gls_no_outlier  8 235.8413
gls_reduced     6 230.6036</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">ggpredict</span>(gls_reduced), <span class="at">show_data=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.
Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$Treatment</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
$Nutrient</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="WEEK-4_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>